### ISSUE TITLE
versioning order does not understand the integer values in the version number

### ISSUE THREAD

**Issue by MiguelAlho** [BenPhegan/vagrantshadow#11]
Seems the version component is ordered as a string, instead of breaking up the version number into numeric components and ordering on that. So, a version 0.3.9 is considered greater then 0.3.10.

**Comment by MiguelAlho** [comment]
it wasn't so much the undertanding of the values (version.compare works correctly) but something in the loop always set the current version to the version in the loop's iteration. Maybe the `&v` ? I'm a noob with Go, but if it's setting the current version reference to the address contained in v, then in each itteration that would change automatically?

**Comment by BenPhegan** [comment]
Fixed by PR #12
